# Generated by Django 4.2.16 on 2024-09-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado')], max_length=1)),
                ('carg_hours', models.IntegerField()),
                ('date_of_course', models.DateField(help_text='Formato: dd/mm/aaaa')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Cadastros de Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-date_of_course'],
            },
        ),
    ]
