# Generated by Django 4.2.16 on 2024-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('senha', models.CharField(max_length=50)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
